version: '3'
services:
  cloudsql-proxy:
    container_name: morellis-cloud-sql-proxy
    image: gcr.io/cloudsql-docker/gce-proxy:1.11
    command: /cloud_sql_proxy --dir=/cloudsql -instances=<${GCP_MYSQL_INSTANCE}>=tcp:0.0.0.0:3306 -credential_file=/credentials.json
    ports:
      - 3306:3306
    volumes:
      - ./morellis-api-a857005c832b.json:/credentials.json
    restart: always
    env_file:
      - ./.env
    networks:
      - morellis-net

  db:
    container_name: morellis-mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: morellis
      MYSQL_USER: morellis
      MYSQL_PASSWORD: E4j+#2G^8Pa=^Nn9
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
    ports:
      - "33061:3306"
  db-test:
    container_name: morellis-mysql-test
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: morellistest
      MYSQL_USER: morellistest
      MYSQL_PASSWORD: testpass
    volumes:
      - ./sql/test:/docker-entrypoint-initdb.d
    ports:
      - "33062:3306"

networks:
  morellis-net: